### ISSUE TITLE
Usage with ReactFire

### ISSUE THREAD

**Issue by Doesntmeananything** [davideast/hnpwa-api#18]
Hi! I'm wondering if it's possible to use [api.hnpwa.com/v0/](api.hnpwa.com/v0/) with Firebase clients, namely [ReactFire](https://github.com/FirebaseExtended/reactfire)?

In particular:

1. How would the `firebaseConfig` look like?
2. How would topics like `news`, `jobs`, `user`, etc. map to collections?

Slightly modifying the basic example from ReactFire:

```javascript
import React from 'react';
import { FirebaseAppProvider, useFirestoreDocData, useFirestore, SuspenseWithPerf } from 'reactfire';

// 1. 👇 Is it possible to add some sort of hnpwa-api config here?
const firebaseConfig = {
  /* Add your config from the Firebase Console */
};

function Story() {
  // 2. 👇 What is the correct way to fetch resources?
  const storyRef = useFirestore().collection('news').doc('1');
  const story = useFirestoreDocData(storyRef);

  return <h1>{story.title}</h1>;
}

function App() {
  return (
    <FirebaseAppProvider firebaseConfig={firebaseConfig}>
      <SuspenseWithPerf fallback={<p>loading...</p>} traceId={'load-story-status'}>
        <Story />
      </SuspenseWithPerf>
    </FirebaseAppProvider>
  );
}
```

Thanks!

**Comment by davideast** [comment]
Hey, @Doesntmeananything.

This can't actually be used with ReactFire because it works over a HTTP and not via the Firebase client SDKs. If you don't need realtime capabilities then using `fetch` or a client like `react-query` will work best. If you do need realtime, then you'll have to do some more difficult work against the [official HN API](https://github.com/HackerNews/API).
